#!/bin/sh
#根据进程名杀死进程
 
PROCESS=`ps -ef|grep 'Application'|grep -v grep|grep -v PPID|awk '{ print $2}'`
for i in $PROCESS
do
  echo "Kill the EasyProxy process [ $i ]"
  kill -9 $i
done
echo 'Web Application has been killed'
